logging:
  level:
    root: info
    com.psc.sample: debug
server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
      
  hikari:
    jdbc-url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver  
    username: sa
    password: 1234
  jpa:
    over-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate:
        ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 536851246325-qqeh57qjmd3mdrvf60osq0q30cb8gdkg.apps.googleusercontent.com
            client-secret: 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
            scope: email
          facebook:
            client-id: 574351927141622
            client-secret: 5de13680790e9f781337e3723e756b3f
            scope:
              - email
              - public_profile
          naver:
           client-id: QNVLhQWHiRZOoyWrzPia
           client-secret: gtS0fOc4Yh
           redirect-uri: http://localhost:8080/login/oauth2/code/naver
           authorization-grant-type: authorization_code
           scope: email
           client-name: Naver
          kakao:
            clientId: 079ee3884d6284a30d1da43a4a790267
            clientSecret: lQ55J4AZDNW1KAkfPFOgWnRhRhzrzKWG
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
            - profile_nickname
            - profile_image
            - account_email
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https:openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
      
