logging:
  level:
    root: info
    com.psc.sample: debug
server:
  port: 80
spring:
 application:
  name: oauth2
 jpa:
  hibernate:
    ddl-auto: update
    use-new-id-generator-mappings: true
  show-sql: true
  properties:
    hibernate:
      dialect: org.h2.Driver
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: ga
    password:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 419797364281-fl6vphdht6v359b86b4tr9tmm6nmk4fb.apps.googleusercontent.com
            client-secret: 0yCPQIBQ4DDzRlwnOsWfkJkP
            scope: email
          naver:
           client-id: QNVLhQWHiRZOoyWrzPia
           client-secret: yPrk9prEai
           redirect-uri: http://localhost/login/oauth2/code/naver
           authorization-grant-type: authorization_code
           scope: email
           client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https:openapi.naver.com/v1/nid/me
            user-name-attribute: response
      